profiles:
  lower_core_v1:
    - wyckoff_stage
    - exh_abs_pa_current_bar
    - exh_abs_pa_prior_bar
    - sig_vol_current_bar
    - sig_vol_prior_bar
    - spy_qqq_vol_ma_ratio
    - ma_trend_bullish
    - ma_trend_bearish
    - macdv_core_bull
    - macdv_core_bear
    - ttm_squeeze_pro

  middle_core_v1:
    - wyckoff_stage
    - exh_abs_pa_prior_bar
    - macdv_guard
    - sig_vol_current_bar
    - spy_qqq_vol_ma_ratio

  upper_core_v1:
    - wyckoff_stage
    - exh_abs_pa_prior_bar
