profiles:
  lower_core_v1:
    - sma_8
    - ema_8
    - ema_21
    - wema_14
    - ema_8_slope
    - ema_21_slope
    - volume_sma_20
    - atr_14
    - wyckoff_stage
    - exh_abs_pa_current_bar
    - exh_abs_pa_prior_bar
    - significant_volume
    - spy_qqq_vol_ma_ratio
    - vol_regime
    - entry_signal

  middle_core_v1:
    - sma_8
    - ema_8
    - ema_21
    - wema_14
    - ema_8_slope
    - ema_21_slope
    - volume_sma_20
    - atr_14
    - wyckoff_stage
    - exh_abs_pa_prior_bar
    - significant_volume
    - spy_qqq_vol_ma_ratio
    - vol_regime
    - entry_signal

  upper_core_v1:
    - sma_8
    - ema_8
    - ema_21
    - wema_14
    - ema_8_slope
    - ema_21_slope
    - volume_sma_20
    - atr_14
    - wyckoff_stage
    - exh_abs_pa_prior_bar
    - vol_regime
    - entry_signal
