profiles:
  lower_core_v1:
    - wyckoff_stage
    - exh_abs_pa_current_bar
    - exh_abs_pa_prior_bar
    - significant_volume
    - spy_qqq_vol_ma_ratio
    - ma_trend_cloud
    - macdv_core
    - ttm_squeeze_pro

  middle_core_v1:
    - wyckoff_stage
    - exh_abs_pa_prior_bar
    - significant_volume
    - spy_qqq_vol_ma_ratio

  upper_core_v1:
    - wyckoff_stage
    - exh_abs_pa_prior_bar
