indicators:
  stocks:
    intraday_130m:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 15
        slow_len: 30
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 126
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 126
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 30
        timeframe_name: "intraday_130m"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 15

      macdv_core:
        id: macdv
        z: 1
        
      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    daily:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 5
        int_len: 13
        slow_len: 21
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 126
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 126
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 21
        timeframe_name: "daily"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 10

      macdv_core:
        id: macdv
        z: 0

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 0

    weekly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 13
        slow_len: 26
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 104
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 104
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 104
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 104
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 26
        timeframe_name: "weekly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 13

      macdv_core:
        id: macdv
        z: 0

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 0

    monthly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 12
        slow_len: 24
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 60
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 60
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 60
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 60
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 24
        timeframe_name: "monthly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 12

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    quarterly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 5
        int_len: 10
        slow_len: 20
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 50
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 50
        z: 1
      
      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 50
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 50
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 20
        timeframe_name: "quarterly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 10

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    yearly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 5
        int_len: 10
        slow_len: 20
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 50
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 50
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 50
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 50
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 20
        timeframe_name: "yearly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 10

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

  futures:
    intraday_1h:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 7
        int_len: 15
        slow_len: 23
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 115
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 115
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 115
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 115
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 23
        timeframe_name: "intraday_1h"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 10

      macdv_core:
        id: macdv
        z: 1
        
      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    intraday_4h:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 15
        slow_len: 30
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 126
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 126
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 30
        timeframe_name: "intraday_4h"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 12

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    daily:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 5
        int_len: 13
        slow_len: 21
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 126
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 126
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 126
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 21
        timeframe_name: "daily"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 10

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    weekly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 13
        slow_len: 26
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 104
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 104
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 104
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 104
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 26
        timeframe_name: "weekly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 13

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1

    monthly:
      wyckoff_stage:
        id: wyckoff_stage
        fast_len: 6
        int_len: 12
        slow_len: 24
        vma_length_source: "fast"

      exh_abs_pa_current_bar:
        id: exh_abs_price_action
        lookback_period: 60
        z: 0

      exh_abs_pa_prior_bar:
        id: exh_abs_price_action
        lookback_period: 60
        z: 1

      sig_vol_current_bar:
        id: significant_volume
        lookback_period: 60
        z: 0

      sig_vol_prior_bar:
        id: significant_volume
        lookback_period: 60
        z: 1

      spy_qqq_vol_ma_ratio:
        id: spy_qqq_volume_ma_ratio
        length: 24
        timeframe_name: "monthly"

      ma_trend_cloud:
        id: movingavg_trend_cloud
        fast_length: 12

      macdv_core:
        id: macdv
        z: 1

      macdv_guard:
        id: macdv_guard
        z: 0

      ttm_squeeze_pro:
        id: ttm_squeeze_pro
        z: 1
