stocks:
  stocks_a_mqy_shortlist:
    universe: shortlist_stocks
    
    lower_tf: monthly
    lower_profile: lower_core_v1
    
    middle_tf: quarterly
    middle_profile: middle_core_v1
    
    upper_tf: yearly
    upper_profile: upper_core_v1

    
  stocks_a_mqy_all:
    universe: options_eligible
    
    lower_tf: monthly
    lower_profile: lower_core_v1
    
    middle_tf: quarterly
    middle_profile: middle_core_v1
    
    upper_tf: yearly
    upper_profile: upper_core_v1
    

  stocks_b_wmq_shortlist:
    universe: shortlist_stocks
    
    lower_tf: weekly
    lower_profile: lower_core_v1
    
    middle_tf: monthly
    middle_profile: middle_core_v1
    
    upper_tf: quarterly
    upper_profile: upper_core_v1
    

  stocks_b_wmq_all:
    universe: options_eligible
    
    lower_tf: weekly
    lower_profile: lower_core_v1
    
    middle_tf: monthly
    middle_profile: middle_core_v1
    
    upper_tf: quarterly
    upper_profile: upper_core_v1
    

  stocks_c_dwm_shortlist:
    universe: shortlist_stocks
    
    lower_tf: daily
    lower_profile: lower_core_v1
    
    middle_tf: weekly
    middle_profile: middle_core_v1
    
    upper_tf: monthly
    upper_profile: upper_core_v1
    

  stocks_c_dwm_all:
    universe: options_eligible
    
    lower_tf: daily
    lower_profile: lower_core_v1
    
    middle_tf: weekly
    middle_profile: middle_core_v1
    
    upper_tf: monthly
    upper_profile: upper_core_v1
    

  stocks_d_130mdw_shortlist:
    universe: shortlist_stocks
    
    lower_tf: intraday_130m
    lower_profile: lower_core_v1
    
    middle_tf: daily
    middle_profile: middle_core_v1
    
    upper_tf: weekly
    upper_profile: upper_core_v1
    


futures:
  futures_1_1h4hd_shortlist:
    universe: shortlist_futures
    
    lower_tf: intraday_1h
    lower_profile: lower_core_v1
    
    middle_tf: intraday_4h
    middle_profile: middle_core_v1
    
    upper_tf: daily
    upper_profile: upper_core_v1
    

  futures_2_4hdw_shortlist:
    universe: shortlist_futures
    
    lower_tf: intraday_4h
    lower_profile: lower_core_v1
    
    middle_tf: daily
    middle_profile: middle_core_v1
    
    upper_tf: weekly
    upper_profile: upper_core_v1
    

  futures_3_dwm_shortlist:
    universe: shortlist_futures
    
    lower_tf: daily
    lower_profile: lower_core_v1
    
    middle_tf: weekly
    middle_profile: middle_core_v1
    
    upper_tf: monthly
    upper_profile: upper_core_v1
