stocks:
  intraday_130m:
    session: regular
    window_bars: 300
  daily:
    session: regular
    window_bars: 300
  weekly:
    session: regular
    window_bars: 300
  monthly:
    session: regular
    window_bars: 250
  quarterly:
    session: regular
    window_bars: 250

futures:
  hourly:
    session: extended
    window_bars: 250
  four_hour:
    session: extended
    window_bars: 300
  daily:
    session: extended
    window_bars: 300
  weekly:
    session: extended:
    window_bars: 250
  monthly:
    session: extended
    window_bars: 250
